# Generated by Django 2.2.16 on 2022-05-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
