# Generated by Django 2.2.16 on 2022-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220518_1147'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_constraints',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
